[package]
name = "barbaria_client"
version = "0.1.0"
authors = ["janek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.10.0"
glfw = "0.41.0"